//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncubXpertInvoicing.Dl.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterProduct
    {
        public MasterProduct()
        {
            this.OrderLineItems = new List<OrderLineItem>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public int Rate { get; set; }
        public int GstRate { get; set; }
    
        public virtual IList<OrderLineItem> OrderLineItems { get; set; }
    }
}
